Fix `tkinter` not working in `python`
The env variable would prevent auto-detection of `tcl-tk` at `pyenv install
<version>` time and result in:
```
$ python -c 'import tkinter'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import tkinter
  File "/Users/<username>/.pyenv/versions/3.13.3/lib/python3.13/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

Version 9 of `tcl-tk` does not seem to be perfectly supported yet, so
need to pin it.

After this, need to reinstall via:
```
pyenv install 3.14.7
pyenv global 3.14.7
```